name: flutter_webview
description: Example showing how to serve files from asset to Webview.

environment:
  sdk: ">=2.0.0-dev.65 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webview_plugin: ^0.2.1
  jaguar: ^2.2.1
  jaguar_flutter_asset: ^2.2.0
  cupertino_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  jaguar_flutter_asset:
    path: ../jaguar_flutter_asset

flutter:
  uses-material-design: true

  assets:
    - assets/index.html
    - assets/css/main.css
    - assets/css/styles.css
    - assets/help/index.html
    - assets/img/jaguar.jpg
    - assets/index.html
